CREATE SCHEMA IF NOT EXISTS kirill_skorikov;
SET search_path TO kirill_skorikov;
CREATE TABLE IF NOT EXISTS app_users (
 id integer PRIMARY KEY, username text NOT NULL, password_hash text NOT NULL
);
ALTER TABLE app_users DROP CONSTRAINT IF EXISTS app_users_username_key;
CREATE TABLE IF NOT EXISTS services (
 id integer PRIMARY KEY, name text NOT NULL, duration_minutes integer NOT NULL CHECK(duration_minutes > 0), specialty integer NOT NULL
);
CREATE TABLE IF NOT EXISTS specialists (
 id integer PRIMARY KEY, name text NOT NULL, specialty integer NOT NULL
);
CREATE TABLE IF NOT EXISTS slots (
 id integer PRIMARY KEY, specialist_id integer NOT NULL REFERENCES specialists(id),
 starts_at timestamp NOT NULL, ends_at timestamp NOT NULL, CHECK(ends_at > starts_at)
);
CREATE TABLE IF NOT EXISTS bookings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id integer NOT NULL REFERENCES app_users(id),
 service_id integer NOT NULL REFERENCES services(id),
 slot_id integer NOT NULL REFERENCES slots(id),
 status text NOT NULL CHECK(status IN ('active','cancelled')),
 created_at timestamp NOT NULL DEFAULT timestamp '2026-10-08 00:00:00'
);
